dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: decidep8
  strategy: git
  api_key:
    secure: M2MzfRz6UJj/oRpm/51iYmfElzwYZlHX/1pNlKbj084TyUvDKtFFiwGjieuIxUbv7TEfUgat3Nlo0UyobZchfdekIurCu6ZytBCzbFXRXnKIWgRPhbXumTlh1cfXYapl5xs+LSrc1EabpLbFqhg+10z5S9jheJfBLfJzEXMqEEq8JD4/4iPdZqMxMhAkuSj6kEr7PeN4nZqyuLQJYfAwK6A/PgnvZmG08NwYkfvdUeFHk7gu3iIGhe11ptAeAfatFqLkpmaic2nXX+GUWLA+JJIXexMzweyTojVhDWgdBguCOzvtnBE08QlZShl2jKo1CnFXVZuXOq8V/Aj5vmYLm9+On6cD+tREyFFQ4Nbu8x/8amJlMM8q9ys7WN9m2wgcmNua0vu1LUyx3eFs/99B/tdgtzDKw6ouj8HxTclzYUIEno8eGXn5Y3ZBMyDjAJSt0NktdQi0oUqq3YGqnGZsq0sHpQt5lLCEp08MnRN86z5B4ZVkyEcsORgTf5IRPydO9ebLc6/5Wc5RwEU3oTCU+rrVKUMlbgY4hm3ahkiXrK32JyfQJBNb0ljFsyP4j7IpFPM37O6Nhj5thg8fhFEA9oiWAU4beJk+x30JH6AkDuggTIBEzjV4SBXjroEzc9QcpMXbUP3gtMSk0tzVQBcl3nWJsB160gHIbpf1vaMegeg=
